CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Уникальный идентификатор записи
    name VARCHAR(255) NOT NULL,                  -- Название категории
    CONSTRAINT pk_stats PRIMARY KEY (id)
);
