-- пользователи
CREATE TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT users_email_unique UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Уникальный идентификатор записи
    name VARCHAR(255) NOT NULL,                  -- Название категории
    CONSTRAINT pk_stats PRIMARY KEY (id)
);
