-- пользователи
create TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT users_email_unique UNIQUE (email)
);
create TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Уникальный идентификатор записи
    name VARCHAR(50) NOT NULL,                  -- Название категории
    CONSTRAINT pk_stats PRIMARY KEY (id),
    CONSTRAINT categories_unique UNIQUE (name)
);

CREATE TABLE IF NOT exists locations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
lat decimal NOT NULL,
lon decimal NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE  IF NOT exists events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	annotation VARCHAR(2000) NOT NULL,
	category_id int8 NOT NULL,
	initiator_id int8 NOT NULL,
	location_id int8 NULL,
	paid bool NOT NULL,
	request_moderation bool NOT NULL,
	title VARCHAR(120) NOT NULL,
	state varchar(255) NOT NULL,
	views int4 NOT NULL,
	description VARCHAR(7000) NOT NULL,
	event_date time NULL,
	participant_limit int4 NOT NULL,
	created_on time NULL,
	published_on time NULL,
	state_action text NULL,
	CONSTRAINT pk_events PRIMARY KEY (id),
	CONSTRAINT events_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
	CONSTRAINT events_users_fk FOREIGN KEY (initiator_id) REFERENCES public.users(id),
	CONSTRAINT fk_location FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE
);



